import {
  AppMenuIcon,
  BellIcon,
  CancelIcon,
  MenuIcon,
  SearchIcon,
  ShoppingBagIcon,
  UserCircleIcon,
  InboxIcon,
  ProfileIcon,
  SettingsIcon,
  BucketIcon,
  DollarCircleIcon,
  LogoutIcon,
  MessageDownloadIcon,
  UserAddIcon,
  HeartIcon,
  ChatBubbleIcon,
  VideoIcon,
  EyeIcon,
} from '../components/Icons';

export const Icons = {
  search: SearchIcon,
  menu: MenuIcon,
  cancel: CancelIcon,
  bell: BellIcon,
  apps: AppMenuIcon,
  shoppingBag: ShoppingBagIcon,
  userCircle: UserCircleIcon,
  inbox: InboxIcon,
  profile: ProfileIcon,
  settings: SettingsIcon,
  bucket: BucketIcon,
  dollarCircle: DollarCircleIcon,
  logout: LogoutIcon,
  messageDownload: MessageDownloadIcon,
  userAdd: UserAddIcon,
  heart: HeartIcon,
  chatBubble: ChatBubbleIcon,
  video: VideoIcon,
  eye: EyeIcon,
};
