import {
  AppMenuIcon,
  BellIcon,
  CancelIcon,
  MenuIcon,
  SearchIcon,
  ShoppingBagIcon,
  UserCircleIcon,
  InboxIcon,
  ProfileIcon,
  SettingsIcon,
  BucketIcon,
  DollarCircleIcon,
  LogoutIcon,
} from '../components/Icons';

export const Icons = {
  search: SearchIcon,
  menu: MenuIcon,
  cancel: CancelIcon,
  bell: BellIcon,
  apps: AppMenuIcon,
  shoppingBag: ShoppingBagIcon,
  userCircle: UserCircleIcon,
  inbox: InboxIcon,
  profile: ProfileIcon,
  settings: SettingsIcon,
  bucket: BucketIcon,
  dollarCircle: DollarCircleIcon,
  logout: LogoutIcon,
};
